services:
  - type: web
    name: stripe-course
    runtime: php
    buildCommand: "composer install && php artisan migrate --force"
    startCommand: "heroku-php-nginx public/"
    envVars:
      - key: APP_NAME
        value: "Stripe Course"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: sqlite
      - key: LOG_CHANNEL
        value: stderr
